SELECT * from dataset_1;
SELECT weather, temperature FROM dataset_1;
select * from dataset_1 LIMIT 10;
SELECT DISTINCT passanger from dataset_1;
select * from dataset_1 where destination = 'Home';
select * from dataset_1 order by coupon;
select destination as destination from dataset_1;
select occupation from dataset_1 group by occupation;
select weather, AVG(temperature) as avg_temp from dataset_1 group by weather;
select weather, count(distinct temperature) as count_distinct_temp from dataset_1 group by weather;
select weather, sum(temperature) as sum_temp from dataset_1 group by weather;
select weather, min(temperature) as min_temp from dataset_1 group by weather;
select weather, max(temperature) as max_temp from dataset_1 group by weather;
SELECT occupation FROM dataset_1 GROUP BY occupation HAVING occupation='Student';
SELECT DISTINCT destination FROM(SELECT * FROM dataset_1 UNION SELECT * FROM table_to_union);
SELECT a.destination,a.time,b.part_of_day FROM dataset_1 a INNER JOIN table_to_join b ON a.time=b.time;
SELECT destination ,passanger FROM(SELECT*FROM dataset_1 WHERE passanger = 'Alone');
SELECT * FROM dataset_1 WHERE weather LIKE 'Sun%';
SELECT DISTINCT temperature FROM dataset_1 WHERE temperature BETWEEN 29 AND 75;
SELECT occupation FROM dataset_1 WHERE occupation IN('Sales & Related','Management');