# -*- coding: utf-8 -*-
"""opencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXEjoB4jOmOpVDmBSA_n99jyeC-Y4Gmq

# Open CV
"""

import cv2

import numpy as np

input = cv2.imread('/content/lamborghini car.jpeg')

input

cv2.imshow('lamborghini',input)
cv2.waitKey()
cv2.destroyAllWindows()

print('Height of Image:',int(input.shape[0]),'pixels')
print('Width of Image:',int(input.shape[1]),'pixels')

cv2.imwrite('output.jpg',input)

import os
os.getcwd()



